version: '3' 
services: 
  db:
    image: postgres:9.3-alpine  
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: always 
    environment:
      POSTGRES_USER: roomresrv
      POSTGRES_PASSWORD: roomresrv

  app:  
    build: .
    ports:
      - "80:80"
    environment: 
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      # Dummy
      DATABASE_USER: roomresrv
      DATABASE_PASSWORD: roomresrv
      RAILS_SERVE_STATIC_FILES: 1

volumes:
  postgresql-data:
