version: '3' 
services: 
  db:
    image: postgres:12-alpine  
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    restart: always 
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  app:  
    build: .
    ports:
      - "7071:80"
    env_file: .env

volumes:
  postgresql-data:
